services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - webnet
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - webnet
    restart: always

volumes:
  database:

networks:
  webnet:

