include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/rules.yaml"

  - local: "/.gitlab-ci/jobs/docker.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 8080:8080"


