version: "3.8"

services:
    main-backend:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: main-backend
        ports:
        - "8080:8080"
        environment:
            SERVER_PORT: 8080
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_JDBC_URL: jdbc:postgresql://db:5432/postgres
            RANDOM_SECRET: A1b2C3d4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2
        depends_on:
            -   db

    db:
        image: postgres:latest
        container_name: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data: